import { GetFoodsResponse } from "~~/types";

export default <GetFoodsResponse>[
  {
    id: 1,
    name: "Pão de forma Integral Wikibold",
    weight: 2,
    carb: 20,
    prot: 6.3,
    tfat: 1.7,
    fiber: 3.5,
    sodium: 242,
    calories: 122,
    unit: "fatia",
  },
  {
    id: 2,
    name: "Requeijão Classe A",
    weight: 30,
    carb: 0,
    prot: 3.7,
    tfat: 6.9,
    fiber: 0,
    sodium: 135,
    calories: 77,
    unit: "g",
  },
  {
    id: 3,
    name: "Macarrão Integral GALO",
    weight: 140,
    carb: 38,
    prot: 7,
    tfat: 1,
    fiber: 5,
    sodium: 0,
    calories: 274,
    unit: "g",
  },
  {
    id: 4,
    name: "Presunto Perdigão",
    weight: 40,
    carb: 0.8,
    prot: 6.9,
    tfat: 1.2,
    fiber: 0,
    sodium: 464,
    calories: 43,
    unit: "g",
  },
  {
    id: 5,
    name: "Peito de Frango Pif Paf cru",
    weight: 100,
    carb: 0,
    prot: 23,
    tfat: 4.1,
    fiber: 0,
    sodium: 81,
    calories: 128,
    unit: "g",
  },
  {
    id: 6,
    name: "Ovo tam. Médio inteiro",
    weight: 1,
    carb: 0.8,
    prot: 6,
    tfat: 5,
    fiber: 0,
    sodium: 60,
    calories: 83,
    unit: "unidade",
  },
  {
    id: 7,
    name: "Clara de Ovo",
    weight: 1,
    carb: 0,
    prot: 4,
    tfat: 0.1,
    fiber: 0,
    sodium: 55,
    calories: 17,
    unit: "unidade",
  },
  {
    id: 8,
    name: "Farofa Tradicional Yoki",
    weight: 35,
    carb: 28,
    prot: 0.4,
    tfat: 3.2,
    fiber: 2.8,
    sodium: 183,
    calories: 143,
    unit: "g",
  },
  {
    id: 9,
    name: "Molho de Tomate Tradicional Fugini",
    weight: 60,
    carb: 8,
    prot: 1.1,
    tfat: 1,
    fiber: 1.3,
    sodium: 316,
    calories: 40,
    unit: "g",
  },
  {
    id: 10,
    name: "Albumina Naturovos 80% ",
    weight: 28,
    carb: 0,
    prot: 24,
    tfat: 0,
    fiber: 0,
    sodium: 408,
    calories: 94,
    unit: "g",
  },
  {
    id: 11,
    name: "Leite Desnatado Classe A",
    weight: 200,
    carb: 9.3,
    prot: 6.2,
    tfat: 0.4,
    fiber: 0,
    sodium: 140,
    calories: 66,
    unit: "g",
  },
  {
    id: 12,
    name: "Pão de Forma Integral Seven Boys Trigo e Linho Leve",
    weight: 50,
    carb: 14,
    prot: 10,
    tfat: 0.8,
    fiber: 4.8,
    sodium: 201,
    calories: 103,
    unit: "fatia",
  },
  {
    id: 13,
    name: "Ricota Tia Lurdes",
    weight: 30,
    carb: 0.9,
    prot: 3.4,
    tfat: 3.9,
    fiber: 0,
    sodium: 50,
    calories: 52,
    unit: "g",
  },
  {
    id: 14,
    name: "Granola GRINGS Cerealle Banana e Mel",
    weight: 40,
    carb: 26.5,
    prot: 4,
    tfat: 4,
    fiber: 3.3,
    sodium: 4,
    calories: 147,
    unit: "g",
  },
  {
    id: 15,
    name: "Banana Nanica",
    weight: 1,
    carb: 16.66,
    prot: 0.98,
    tfat: 0.07,
    fiber: 1.33,
    sodium: 0,
    calories: 64,
    unit: "unidade",
  },
  {
    id: 16,
    name: "Casein Gold Standard ON",
    weight: 33,
    carb: 3,
    prot: 24,
    tfat: 1,
    fiber: 1,
    sodium: 240,
    calories: 120,
    unit: "g",
  },
  {
    id: 17,
    name: "WHEY Cor-Performance CELLUCOR",
    weight: 13,
    carb: 1,
    prot: 10,
    tfat: 0.6,
    fiber: 0,
    sodium: 47,
    calories: 52,
    unit: "g",
  },
  {
    id: 18,
    name: "Sardinha Ao Molho COQUEIRO",
    weight: 60,
    carb: 0,
    prot: 14,
    tfat: 3.1,
    fiber: 0,
    sodium: 335,
    calories: 83,
    unit: "g",
  },
  {
    id: 19,
    name: "Pão de Forma 14 Grãos Nutrella",
    weight: 2,
    carb: 17,
    prot: 7.1,
    tfat: 1.9,
    fiber: 3.5,
    sodium: 159,
    calories: 114,
    unit: "fatia",
  },
  {
    id: 20,
    name: "Aveia em Flocos Yoki",
    weight: 30,
    carb: 16,
    prot: 5,
    tfat: 2.4,
    fiber: 3.1,
    sodium: 0,
    calories: 107,
    unit: "g",
  },
  {
    id: 21,
    name: "Arroz Parboilizado Camil Cozido",
    weight: 135,
    carb: 35.2,
    prot: 3.9,
    tfat: 0.5,
    fiber: 1.2,
    sodium: 0,
    calories: 167,
    unit: "g",
  },
  {
    id: 22,
    name: "Pão de Milho Seven Boys",
    weight: 1.5,
    carb: 26,
    prot: 5.7,
    tfat: 2.7,
    fiber: 1.3,
    sodium: 106,
    calories: 150,
    unit: "fatia",
  },
  {
    id: 23,
    name: "Pão de Forma Castanha Nutrella",
    weight: 1.5,
    carb: 17,
    prot: 8.2,
    tfat: 2.8,
    fiber: 3.4,
    sodium: 151,
    calories: 125,
    unit: "fatia",
  },
  {
    id: 24,
    name: "Carne Bovina Patinho Cru",
    weight: 100,
    carb: 0,
    prot: 35.9,
    tfat: 6.5,
    fiber: 0,
    sodium: 60.3,
    calories: 219,
    unit: "g",
  },
  {
    id: 25,
    name: "Abacate",
    weight: 100,
    carb: 6,
    prot: 1.2,
    tfat: 8.4,
    fiber: 6,
    sodium: 0,
    calories: 96,
    unit: "g",
  },
  {
    id: 26,
    name: "Nesfit Cacau e Cereais",
    weight: 5,
    carb: 20,
    prot: 2.4,
    tfat: 4.6,
    fiber: 2.1,
    sodium: 92,
    calories: 129,
    unit: "unidade",
  },
  {
    id: 27,
    name: "Bisnaguinha Integral TRIGO VITA",
    weight: 3,
    carb: 25,
    prot: 5.4,
    tfat: 2,
    fiber: 2.5,
    sodium: 206,
    calories: 145,
    unit: "unidade",
  },
  {
    id: 28,
    name: "Feijão Pronto CAMIL s/ tempero",
    weight: 125,
    carb: 15,
    prot: 6,
    tfat: 0,
    fiber: 6,
    sodium: 0,
    calories: 92,
    unit: "g",
  },
  {
    id: 29,
    name: "Bolacha Maizena Integral Marilan",
    weight: 6.5,
    carb: 21,
    prot: 2.6,
    tfat: 3.9,
    fiber: 1.2,
    sodium: 66,
    calories: 131,
    unit: "unidade",
  },
  {
    id: 30,
    name: "Albumina GROWTH Chocolate",
    weight: 30,
    carb: 2.5,
    prot: 23,
    tfat: 0,
    fiber: 0,
    sodium: 408,
    calories: 102,
    unit: "g",
  },
  {
    id: 31,
    name: "Cream Cracker MARILAN Manteiga",
    weight: 6,
    carb: 20,
    prot: 3.5,
    tfat: 3.8,
    fiber: 1,
    sodium: 210,
    calories: 129,
    unit: "unidade",
  },
  {
    id: 32,
    name: "Cereale Bauducco Cacau e Castanhas",
    weight: 4.5,
    carb: 16,
    prot: 2.7,
    tfat: 5,
    fiber: 2.5,
    sodium: 75,
    calories: 120,
    unit: "unidade",
  },
  {
    id: 33,
    name: "Bel Vita Cacau e Cereais",
    weight: 3,
    carb: 16,
    prot: 2.2,
    tfat: 4.1,
    fiber: 1.3,
    sodium: 59,
    calories: 113,
    unit: "unidade",
  },
  {
    id: 34,
    name: "Pão de Forma Artesano Pullman",
    weight: 1.5,
    carb: 25,
    prot: 3.9,
    tfat: 1.3,
    fiber: 1.4,
    sodium: 193,
    calories: 127,
    unit: "unidade",
  },
  {
    id: 35,
    name: "Pão de Forma Linea Premium Seven Boys 12 Grãos",
    weight: 1.5,
    carb: 12,
    prot: 8.6,
    tfat: 2.9,
    fiber: 4.2,
    sodium: 174,
    calories: 109,
    unit: "unidade",
  },
  {
    id: 36,
    name: "Cereal Mix Aymoré",
    weight: 4,
    carb: 19,
    prot: 2.7,
    tfat: 5.9,
    fiber: 1.7,
    sodium: 121,
    calories: 140,
    unit: "unidade",
  },
  {
    id: 37,
    name: "Leite Integral",
    weight: 200,
    carb: 9.3,
    prot: 5.9,
    tfat: 6.2,
    fiber: 0,
    sodium: 143,
    calories: 117,
    unit: "ml",
  },
  {
    id: 38,
    name: "Granola Light Kobber",
    weight: 40,
    carb: 29,
    prot: 3,
    tfat: 1,
    fiber: 3.8,
    sodium: 108,
    calories: 135,
    unit: "g",
  },
  {
    id: 39,
    name: "Atum Gomes da Costa Molho de Tomate",
    weight: 60,
    carb: 1.5,
    prot: 7,
    tfat: 3.6,
    fiber: 0,
    sodium: 329,
    calories: 66,
    unit: "g",
  },
  {
    id: 40,
    name: "Milho Verde VAPOR Fugini",
    weight: 130,
    carb: 32,
    prot: 7.4,
    tfat: 0.7,
    fiber: 4.4,
    sodium: 127,
    calories: 157,
    unit: "g",
  },
  {
    id: 41,
    name: "Leite em Pó NINHO Forti+",
    weight: 26,
    carb: 9.9,
    prot: 6.8,
    tfat: 7,
    fiber: 0,
    sodium: 95,
    calories: 130,
    unit: "g",
  },
  {
    id: 42,
    name: "Peito de Frango Cozido",
    weight: 100,
    carb: 0,
    prot: 31,
    tfat: 3.5,
    fiber: 0,
    sodium: 74,
    calories: 165,
    unit: "g",
  },
  {
    id: 43,
    name: "Batata Doce Cozida",
    weight: 100,
    carb: 18.4,
    prot: 0.6,
    tfat: 0.1,
    fiber: 2.2,
    sodium: 3,
    calories: 77,
    unit: "g",
  },
  {
    id: 44,
    name: "Tomate",
    weight: 100,
    carb: 3.1,
    prot: 1.1,
    tfat: 0.2,
    fiber: 1.2,
    sodium: 1,
    calories: 15,
    unit: "g",
  },
  {
    id: 45,
    name: "Pimentão Amarelo Cru",
    weight: 100,
    carb: 6,
    prot: 1.2,
    tfat: 0.4,
    fiber: 1.9,
    sodium: 0,
    calories: 28,
    unit: "g",
  },
  {
    id: 46,
    name: "Pão de Forma Integral PULLMAN 12 Grãos ZERO",
    weight: 2,
    carb: 14,
    prot: 8.7,
    tfat: 2.3,
    fiber: 4.2,
    sodium: 190,
    calories: 113,
    unit: "fatia",
  },
  {
    id: 47,
    name: "Pão Integral NEWBREAD Light",
    weight: 2,
    carb: 25,
    prot: 4.1,
    tfat: 0.2,
    fiber: 2.9,
    sodium: 151,
    calories: 115,
    unit: "fatia",
  },
  {
    id: 48,
    name: "Biscoito de Polvilho ROSA Anel",
    weight: 30,
    carb: 13.6,
    prot: 0,
    tfat: 2.4,
    fiber: 0,
    sodium: 208,
    calories: 80,
    unit: "g",
  },
  {
    id: 49,
    name: "Sobrecoxa sem osso/pele Crua",
    weight: 100,
    carb: 0,
    prot: 17,
    tfat: 9.6,
    fiber: 0,
    sodium: 80,
    calories: 162,
    unit: "g",
  },
  {
    id: 50,
    name: "Biscoito Integral LEV Cacau",
    weight: 1,
    carb: 15,
    prot: 2.8,
    tfat: 4.9,
    fiber: 2.5,
    sodium: 89,
    calories: 116,
    unit: "embalagem",
  },
  {
    id: 51,
    name: "Filé de Peito de Peru Sadia",
    weight: 107,
    carb: 0,
    prot: 24,
    tfat: 3,
    fiber: 0,
    sodium: 104,
    calories: 125,
    unit: "g",
  },
  {
    id: 52,
    name: "Pão de Forma ZERO 12 Grãos Pullman",
    weight: 2,
    carb: 14,
    prot: 8.7,
    tfat: 2.3,
    fiber: 4.2,
    sodium: 190,
    calories: 113,
    unit: "fatia",
  },
  {
    id: 53,
    name: "Biscoito de Arroz Integral Chia e Linhaça CAMIL",
    weight: 13,
    carb: 22,
    prot: 2.7,
    tfat: 2,
    fiber: 1.2,
    sodium: 85,
    calories: 118,
    unit: "unidade",
  },
  {
    id: 54,
    name: "Pãop Integral SevenBoys Castanha e Nozes",
    weight: 1,
    carb: 19,
    prot: 7,
    tfat: 3.9,
    fiber: 3,
    sodium: 162,
    calories: 140,
    unit: "fatia",
  },
  {
    id: 55,
    name: "Abobrinha",
    weight: 100,
    carb: 4,
    prot: 1,
    tfat: 0,
    fiber: 1.4,
    sodium: 0,
    calories: 20,
    unit: "g",
  },
  {
    id: 56,
    name: "Pêra",
    weight: 178,
    carb: 27.1,
    prot: 0.6,
    tfat: 0.2,
    fiber: 5.5,
    sodium: 0,
    calories: 101,
    unit: "unidade",
  },
  {
    id: 57,
    name: "Pasta de Amendoim",
    weight: 15,
    carb: 3,
    prot: 4.1,
    tfat: 7,
    fiber: 1,
    sodium: 0,
    calories: 91,
    unit: "g",
  },
  {
    id: 58,
    name: "Iogurte Natural",
    weight: 100,
    carb: 8.2,
    prot: 5,
    tfat: 0,
    fiber: 0,
    sodium: 0.088,
    calories: 53,
    unit: "ml",
  },
  {
    id: 59,
    name: "Maçã",
    weight: 124,
    carb: 17.12,
    prot: 0.32,
    tfat: 0.21,
    fiber: 3,
    sodium: 0.00124,
    calories: 65,
    unit: "unidade",
  },
  {
    id: 60,
    name: "Peito de Peru Fatiado",
    weight: 5,
    carb: 3.8,
    prot: 20,
    tfat: 1.8,
    fiber: 0,
    sodium: 702,
    calories: 110,
    unit: "fatia",
  },
  {
    id: 61,
    name: "Presunto Seara  Pct",
    weight: 3,
    carb: 0.6,
    prot: 6.7,
    tfat: 0.6,
    fiber: 0,
    sodium: 290,
    calories: 34,
    unit: "fatia",
  },
  {
    id: 62,
    name: "Queijo Mussarela Itambé (pct)",
    weight: 1.5,
    carb: 0.6,
    prot: 7.2,
    tfat: 7.2,
    fiber: 0,
    sodium: 128,
    calories: 96,
    unit: "fatia",
  },
  {
    id: 63,
    name: "Leite em Pó Italac Desnatado",
    weight: 20,
    carb: 10,
    prot: 7,
    tfat: 0,
    fiber: 0,
    sodium: 127,
    calories: 72,
    unit: "g",
  },
  {
    id: 64,
    name: "Leite Semi desnatado Classe A",
    weight: 200,
    carb: 9.3,
    prot: 6.1,
    tfat: 2,
    fiber: 0,
    sodium: 140,
    calories: 80,
    unit: "g",
  },
  {
    id: 65,
    name: "Wrap Wikibold Integral",
    weight: 1,
    carb: 22,
    prot: 4.7,
    tfat: 2,
    fiber: 4.8,
    sodium: 217,
    calories: 125,
    unit: "unidade",
  },
  {
    id: 66,
    name: "Batata Crua",
    weight: 30,
    carb: 7.2,
    prot: 0,
    tfat: 0,
    fiber: 0,
    sodium: 0,
    calories: 30,
    unit: "g",
  },
  {
    id: 67,
    name: "Pipoca ",
    weight: 100,
    carb: 74,
    prot: 11,
    tfat: 4.3,
    fiber: 12,
    sodium: 4,
    calories: 375,
    unit: "g",
  },
  {
    id: 68,
    name: "Batata Salsa",
    weight: 100,
    carb: 24,
    prot: 1.1,
    tfat: 1.8,
    fiber: 2.1,
    sodium: 0,
    calories: 80,
    unit: "g",
  },
  {
    id: 69,
    name: "Dextrose",
    weight: 50,
    carb: 47,
    prot: 0,
    tfat: 0,
    fiber: 0,
    sodium: 15,
    calories: 188,
    unit: "g",
  },
  {
    id: 70,
    name: "WHEY Growth 80% Chocolate",
    weight: 30,
    carb: 4,
    prot: 23,
    tfat: 1.6,
    fiber: 0,
    sodium: 53,
    calories: 122,
    unit: "g",
  },
  {
    id: 71,
    name: "Pão Eggs",
    weight: 50,
    carb: 27,
    prot: 3.9,
    tfat: 5.4,
    fiber: 1.1,
    sodium: 117,
    calories: 173,
    unit: "g",
  },
];
